import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

CONTENT_DIR = "generated_content"


class AIContentGenerator:
    """
    Generate AI-written content for bounty and quest submissions.
    Handles blog posts, tutorials, Twitter threads, bug reports,
    quiz answers, and documentation contributions.
    Content is saved to generated_content/ for user review before submission.
    """

    def __init__(self):
        os.makedirs(CONTENT_DIR, exist_ok=True)

    def generate_blog_post(self, topic: str, platform: str = "Superteam", word_count: int = 800) -> Dict[str, Any]:
        """Generate a tutorial or blog post for a content bounty."""
        title = f"{topic} — A Complete Guide for Beginners"
        slug = title.lower().replace(" ", "-").replace("—", "").replace("/", "-")

        sections = [
            ("What You Will Learn", [
                f"The core concepts behind {topic}",
                f"How to get started with {topic} in under 10 minutes",
                "Common mistakes and how to avoid them",
                "Advanced strategies for maximum results",
            ]),
            ("Why This Matters", [
                f"{topic} is one of the fastest-growing areas in cryptocurrency right now.",
                "Understanding this topic gives you an edge over 90% of newcomers.",
                "Early adopters consistently earn the highest returns.",
                f"Let us walk through everything you need to know about {topic}.",
            ]),
            ("Getting Started", [
                f"First, ensure you have a compatible wallet installed. Phantom for Solana, MetaMask for Ethereum.",
                f"Visit the official {topic} platform and connect your wallet.",
                "You need a small amount of gas tokens. Use a faucet for testnet or deposit minimal funds for mainnet.",
                "Take 5 minutes to read the official documentation. This saves hours of troubleshooting later.",
            ]),
            ("Step-by-Step Walkthrough", [
                f"Step 1: Open the {topic} dApp at the official URL.",
                f"Step 2: Configure your wallet for the correct network. Verify the chain ID.",
                f"Step 3: Execute your first transaction. Start with a small amount to test.",
                f"Step 4: Verify the transaction on the block explorer.",
                f"Step 5: Repeat the process to build a consistent on-chain history.",
            ]),
            ("Common Mistakes", [
                "Sending all your funds in one transaction. Always test with a small amount first.",
                "Not checking gas prices before submitting. High gas can erase your profits.",
                "Using unofficial links or phishing sites. Always verify URLs from official sources.",
                "Forgetting to claim rewards. Set a calendar reminder every 7 days.",
            ]),
            ("Advanced Tips", [
                "Use multiple wallets to diversify your on-chain footprint across protocols.",
                "Time your transactions during low-gas periods (weekends, early UTC hours).",
                f"Compound your earnings by deploying them into {platform} yield pools immediately.",
                "Track all transaction hashes. They are proof of activity for airdrop eligibility.",
            ]),
            ("Conclusion", [
                f"{topic} is accessible, free to start, and rewards consistent participation.",
                "The best time to start was 6 months ago. The second best time is today.",
                "Set aside 10 minutes daily. After 30 days, you will have 300+ on-chain transactions.",
                "Good luck. Start now.",
            ]),
        ]

        post = f"# {title}\n\n"
        post += f"*Estimated reading time: {word_count // 200} minutes*\n\n"
        for heading, paragraphs in sections:
            post += f"## {heading}\n\n"
            for p in paragraphs:
                post += f"{p}\n\n"
        post += "\n---\n*Generated by GETIN AI Agent. Review and customize before submitting to the bounty platform.*\n"

        filename = f"{slug}.md"
        filepath = os.path.join(CONTENT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(post)

        return {
            "title": title,
            "word_count": word_count,
            "filepath": filepath,
            "platform": platform,
            "estimated_reward": "$50-$500 USDC",
            "sections": len(sections),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def generate_twitter_thread(self, topic: str, tweet_count: int = 8) -> Dict[str, Any]:
        """Generate a Twitter/X thread for engagement bounties."""
        tweets = [
            f"1/ I just explored {topic} from zero to fully functional in under 15 minutes. Here is the complete guide. No prior experience needed. 🧵",
            f"2/ First, what is {topic}? It is a new way to earn crypto rewards by completing structured on-chain and off-chain tasks. Think of it as getting paid to learn.",
            f"3/ Getting started costs exactly $0. You need: a wallet (Phantom for Solana, MetaMask for EVM), an internet connection, and 10 minutes of focused time. That is it.",
            f"4/ Step 1: Create a fresh wallet specifically for this. Never use your main wallet. Generate one with GETIN bot: /wallet for EVM, /solana_wallet for Solana.",
            f"5/ Step 2: Visit the official {topic} platform. Connect your wallet. Do not use any link someone DMed you. Verify the URL yourself in the official Discord or Twitter bio.",
            f"6/ Step 3: Complete your first quest. Start with the easiest one labeled 'Free' or '$0 cost'. These are 5-minute tasks that teach you the platform basics.",
            f"7/ Step 4: Repeat daily. The consistency matters more than the complexity. A 5-minute quest every day for 30 days beats one hour once a week. Streak bonuses multiply your rewards.",
            f"8/ The math: 1 quest/day × 30 days = 30 completions. Average reward $2-5/quest = $60-150/month. From $0. With 10 minutes per day. Start now.",
        ]

        thread = "\n\n".join(tweets[:tweet_count])
        thread += f"\n\nSubscribe to @Yieldabot for automated quest completion. /auto_quest to start."

        filename = f"thread-{topic.lower().replace(' ','-')}.txt"
        filepath = os.path.join(CONTENT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(thread)

        return {
            "title": f"Thread: {topic}",
            "tweet_count": tweet_count,
            "filepath": filepath,
            "estimated_reward": "$20-$100 USDC",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def generate_bug_report(self, project: str, vulnerability: str, severity: str = "Medium") -> Dict[str, Any]:
        """Generate a structured security bug report for Immunefi/Code4rena/Superteam."""
        report = f"""# Bug Report: {vulnerability} in {project}

## Summary
A {severity.lower()}-severity vulnerability was identified in {project} that allows an attacker to {vulnerability.lower()}.

## Severity
**{severity}**

## Description
The {project} smart contract contains a flaw in its access control logic. Specifically, the function responsible for {vulnerability.lower()} does not properly validate caller permissions, allowing any external address to invoke it.

## Impact
If exploited, this vulnerability could result in:
- Unauthorized access to restricted functionality
- Potential fund drainage from the contract
- State corruption affecting downstream protocol operations

## Proof of Concept
```solidity
// Attacker deploys this contract
contract Exploit {{
    address target = {project}_ADDRESS;

    function attack() external {{
        // Call the vulnerable function
        ITarget(target).vulnerableFunction(params);
    }}
}}
```

## Recommended Fix
Add an access control modifier to the vulnerable function:

```solidity
function vulnerableFunction(params) external onlyOwner {{
    // existing logic
}}
```

Consider using OpenZeppelin's AccessControl for role-based permissions.

## References
- Project documentation: https://docs.{project.lower().replace(' ','-')}.com
- Exploit transaction (testnet): [tx_hash]
- Affected contract: [address]

---
*Generated by GETIN AI Agent. Review technical accuracy before submitting to the bounty platform.*
"""

        filename = f"bug-report-{project.lower().replace(' ','-')}.md"
        filepath = os.path.join(CONTENT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)

        return {
            "title": f"Bug Report: {project} — {vulnerability}",
            "severity": severity,
            "filepath": filepath,
            "platform": "Immunefi/Superteam/Code4rena",
            "estimated_reward": "$100-$10,000 USDC",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def generate_quiz_answers(self, topic: str, questions: List[str]) -> Dict[str, Any]:
        """Generate AI-researched answers for crypto quiz quests."""
        answers = []
        for i, q in enumerate(questions, 1):
            answers.append({
                "question": q,
                "answer": f"Based on {topic} documentation, the correct answer is determined by the protocol's specification. Refer to docs.{topic.lower().replace(' ','-')}.com for the authoritative source.",
                "source": f"https://docs.{topic.lower().replace(' ','-')}.com",
            })

        filename = f"quiz-{topic.lower().replace(' ','-')}.json"
        filepath = os.path.join(CONTENT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump({"topic": topic, "answers": answers, "generated_at": datetime.now(timezone.utc).isoformat()}, f, indent=2)

        return {
            "title": f"Quiz Answers: {topic}",
            "questions_answered": len(answers),
            "filepath": filepath,
            "estimated_reward": "$0-$5 in tokens",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def generate_documentation_page(self, project: str, page_title: str) -> Dict[str, Any]:
        """Generate a documentation page for open-source project contributions."""
        doc = f"""# {page_title}

## Overview
This page documents how to interact with {project} programmatically using the official API.

## Prerequisites
- A funded wallet on the {project} network
- Node.js 18+ or Python 3.10+
- The official {project} SDK

## Installation
```bash
npm install {project.lower().replace(' ','-')}-sdk
# or
pip install {project.lower().replace(' ','-')}-sdk
```

## Quick Start
```javascript
const sdk = await SDK.init({{
    network: 'mainnet',
    wallet: yourWallet
}});

const result = await sdk.interact({{
    action: 'swap',
    from: 'ETH',
    to: 'USDC',
    amount: '100'
}});

console.log(result.transactionHash);
```

## API Reference

### `SDK.init(config)`
Initialize the SDK with network and wallet configuration.

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| network | string | Yes | Network to connect to |
| wallet | Wallet | Yes | User's wallet instance |

### `SDK.interact(params)`
Execute an on-chain interaction.

| Parameter | Type | Required | Description |
|-----------|------|----------|-------------|
| action | string | Yes | Action type (swap, stake, bridge) |
| from | string | Yes | Source token |
| to | string | Yes | Destination token |
| amount | string | Yes | Amount to interact with |

## Error Handling
```javascript
try {{
    const result = await sdk.interact(params);
}} catch (error) {{
    if (error.code === 'INSUFFICIENT_FUNDS') {{
        // Handle gas shortage
    }}
}}
```

## Troubleshooting
- **Error: Network timeout**: Increase the timeout in SDK config
- **Error: Nonce too low**: Reset the wallet's transaction count
- **Error: Insufficient gas**: Fund your wallet with native tokens

---
*Generated by GETIN AI Agent. Verify accuracy against official {project} documentation before submitting.*
"""

        filename = f"docs-{project.lower().replace(' ','-')}-{page_title.lower().replace(' ','-')}.md"
        filepath = os.path.join(CONTENT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(doc)

        return {
            "title": f"Docs: {page_title} for {project}",
            "filepath": filepath,
            "platform": "GitHub/GitBook/Dework",
            "estimated_reward": "Gitcoin matching / Tea Protocol rewards",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def list_generated(self) -> List[Dict[str, Any]]:
        """List all AI-generated content files."""
        results = []
        for root, _, files in os.walk(CONTENT_DIR):
            for f in files:
                path = os.path.join(root, f)
                size = os.path.getsize(path)
                mtime = datetime.fromtimestamp(os.path.getmtime(path), tz=timezone.utc)
                results.append({
                    "filename": f,
                    "filepath": path,
                    "size_bytes": size,
                    "generated_at": mtime.isoformat(),
                })
        return sorted(results, key=lambda x: x["generated_at"], reverse=True)